"""``lps init`` — bootstrap a luplo workspace in the current directory.

Picks an org and a project (existing or newly created) and writes a
``.luplo`` TOML file. The file declares the remote backend and project
binding so subsequent ``lp`` calls in this directory know where to go.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import httpx
import typer

from luplo_cloud.api_client import ApiClient, AuthError
from luplo_cloud.config import CliConfig

LUPLO_FILENAME = ".luplo"


def _render_toml(server_url: str, project_id: str, project_name: str) -> str:
    # Hand-rolled TOML to avoid adding tomli_w as a runtime dep. The shape is
    # fixed, escaping is limited to the project name (quotes/backslashes), and
    # the resulting file round-trips through tomllib.
    safe_name = project_name.replace("\\", "\\\\").replace('"', '\\"')
    return (
        "# Generated by `lps init`. Safe to commit.\n"
        "[backend]\n"
        'type = "remote"\n'
        f'server_url = "{server_url}"\n'
        "\n"
        "[project]\n"
        f'id = "{project_id}"\n'
        f'name = "{safe_name}"\n'
    )


def _pick_org(orgs: list[dict[str, Any]], requested_id: str | None) -> dict[str, Any]:
    if requested_id is not None:
        for row in orgs:
            if row["org"]["id"] == requested_id:
                return row["org"]
        typer.secho(
            f"--org {requested_id} is not in your org list.",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(2)

    if not orgs:
        typer.secho(
            "You don't belong to any organization. Create one at "
            "https://app.luplo.io/onboarding first.",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(1)

    if len(orgs) == 1:
        only = orgs[0]["org"]
        typer.echo(f"Using org: {only['name']} ({only['slug']})")
        return only

    typer.echo("Select an organization:")
    for i, row in enumerate(orgs, start=1):
        o = row["org"]
        typer.echo(f"  {i}. {o['name']} ({o['slug']})")
    choice = typer.prompt("Number", type=int)
    if choice < 1 or choice > len(orgs):
        typer.secho("Out of range.", fg=typer.colors.RED, err=True)
        raise typer.Exit(2)
    return orgs[choice - 1]["org"]


def _pick_project(
    client: ApiClient, org_id: str, org_name: str
) -> tuple[str, str]:
    """Show existing projects with a `+ Create new` option last; return (id, name)."""
    projects = client.list_projects(org_id)
    typer.echo(f"Projects in {org_name}:")
    for i, p in enumerate(projects, start=1):
        label = p.get("name") or p["project_id"]
        typer.echo(f"  {i}. {label}")
    create_idx = len(projects) + 1
    typer.echo(f"  {create_idx}. + Create new project")
    choice = typer.prompt("Number", type=int)
    if choice == create_idx:
        return _create_project_interactive(client, org_id)
    if choice < 1 or choice > len(projects):
        typer.secho("Out of range.", fg=typer.colors.RED, err=True)
        raise typer.Exit(2)
    chosen = projects[choice - 1]
    return chosen["project_id"], chosen.get("name") or chosen["project_id"]


def _create_project_interactive(client: ApiClient, org_id: str) -> tuple[str, str]:
    name = typer.prompt("New project name").strip()
    if not name:
        typer.secho("Empty name.", fg=typer.colors.RED, err=True)
        raise typer.Exit(2)
    return _create_project(client, org_id, name)


def _create_project(client: ApiClient, org_id: str, name: str) -> tuple[str, str]:
    try:
        created = client.create_project(org_id, name)
    except httpx.HTTPStatusError as e:
        typer.secho(
            f"Failed to create project: {e.response.status_code} {e.response.text}",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(1) from None
    return created["project_id"], created.get("name") or created["project_id"]


def _resolve_existing_project(
    client: ApiClient, org_id: str, project_id: str
) -> tuple[str, str]:
    for p in client.list_projects(org_id):
        if p["project_id"] == project_id:
            return p["project_id"], p.get("name") or p["project_id"]
    typer.secho(
        f"--project {project_id} is not a project of the chosen org.",
        fg=typer.colors.RED,
        err=True,
    )
    raise typer.Exit(2)


def run(
    server_url: str = typer.Option(None, "--server", help="API base URL."),
    org_id: str = typer.Option(None, "--org", help="Org UUID (skip the picker)."),
    project_id: str = typer.Option(
        None, "--project", help="Existing project id to bind."
    ),
    new_project: str = typer.Option(
        None, "--new-project", help="Create a new project with this name."
    ),
    force: bool = typer.Option(
        False, "--force", help="Overwrite an existing .luplo in this directory."
    ),
) -> None:
    """Create a ``.luplo`` workspace file in the current directory."""
    if project_id and new_project:
        typer.secho(
            "--project and --new-project are mutually exclusive.",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(2)

    target = Path.cwd() / LUPLO_FILENAME
    if target.exists() and not force:
        typer.secho(
            f"{LUPLO_FILENAME} already exists in this directory. Use --force to overwrite.",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(1)

    cfg = CliConfig.resolve(server_url, None)
    client = ApiClient(cfg)
    try:
        try:
            orgs = client.list_orgs()
        except AuthError as e:
            typer.secho(f"{e}", fg=typer.colors.RED, err=True)
            raise typer.Exit(1) from None

        org = _pick_org(orgs, org_id)
        org_id_str = org["id"]

        if project_id:
            pid, pname = _resolve_existing_project(client, org_id_str, project_id)
        elif new_project:
            pid, pname = _create_project(client, org_id_str, new_project)
        else:
            pid, pname = _pick_project(client, org_id_str, org["name"])
    finally:
        client.close()

    target.write_text(_render_toml(cfg.server_url, pid, pname))
    typer.secho(f"Wrote {target}", fg=typer.colors.GREEN)
    typer.echo(f"  org     : {org['name']} ({org['slug']})")
    typer.echo(f"  project : {pname} ({pid})")
